---
- name: Error handling in Ansible
  hosts: all
  become: true

  tasks:

    - name: Install openssh and openssl
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop:
        - openssh-client
        - openssl
      ignore_errors: true

    - name: Check docker 
      ansible.builtin.command: docker --version
      register: output
      changed_when: false
      failed_when: false

    - name: Print output
      ansible.builtin.debug:
        var: output.stdout

    - name: Install docker 
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes
      when: output.rc != 0
